package tzhai.euler;

/**
 * Problem 2 Even Fibonacci numbers Each new term in the Fibonacci sequence is
 * generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * 
 * @author Zhai Tengfei
 *
 */
public class Problem2 {

	public static int cal() {
		int n1 = 1;
		int n2 = 2;
		int sum = 2;
		int next = 0;
		while (next <= 4E6) {
			if ((next & 1) != 1) {
				sum += next;
			}
			next = n1 + n2;
			n1 = n2;
			n2 = next;
		}
		return sum;
	}

	public static void main(String args[]) {
		System.out.println(Problem2.cal());
	}
}
